version: "3"
#Backend
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/usr/frontend/
      - /usr/frontend/node_modules
    environment:
      - REACT_APP_API_URL="${REACT_APP_API_URL}"
      - DISABLE_ESLINT_PLUGIN=true
    command: npm start

  mern-chat-api:
    build: ./Backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI="${MONGO_URI}"
      - JWT_SECRET="${JWT_SECRET}"
      - PORT:5000
    volumes:
      - ./Backend/:/usr/mern-chat
      - /usr/mern-chat/node_modules
    command: npm start
